# Generated by Django 5.0.4 on 2024-05-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_staff",
            new_name="is_admin",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
