# Generated by Django 5.0.4 on 2024-07-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0006_remove_dictionary_different_languages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
